# Postgresql pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16.4-bullseye
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "h8en9s8N"
        resources:
          requests:
            cpu: 250m
            memory: 250Mi

---
# Expose Postgresql on port 5432
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP  

---  
# ApplicationAccess pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationaccesslite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationaccesslite
  template:
    metadata:
      labels:
        app: applicationaccesslite
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: applicationaccesslite
        image: alastairwyse/applicationaccess:20241014-0907
        ports:
        - containerPort: 5000
        env:
        - name: MODE
          value: "Launch"
        - name: LISTEN_PORT
          value: "5000"
        - name: MINIMUM_LOG_LEVEL
          value: "Warning"
        - name: ENCODED_JSON_CONFIGURATION
          value: "H4sIAAAAAAACA4yTUU/CMBDH3034DmTPmEyNifqmqJEEFB3G52M7RmPXjmuLTsJ3t90UCh3RPS253/2v97+7Veeoa7/oOk1RqREIyJGSBb8FDVNQ2JdCYKqZFNFVd9XAdcIvMKlKtKFoLJXOCZPnYdTzsG3+GAgK1EhqV6nGHmy2UykbFbXgxwppyVL01XYKOxzKkrMUnDzUDQT0q5URtq4vHkBjUOpDUuag+QWKS3XxGEB9WRQgsgkrUBr32HgLrJvf9U9OdLdEoW/MbIZ0z42aM5Hv2dcEE/aFQ1YwJ3ce+77VaUMpy4Gwli2BW+Istt9epRFqYulQ5nlYYyd2J2DK0bU4A66wF3B90JhLqhL7MvbprIhCqHn2mKQzO6jodbZFEk1OuXKKm34xc73Z6Jukd6TJnBCyh2pKLNvJlxTMIXTuNI6DJcGFQYNPJVK9HW1O9v54+D0wbgivf7c/ekFtSCTNXr4KWFrAmRp5ixBapv5xTa0XZfNcLaSWVfzPUW1EE2koxf2JbpCBYJoBt/MHLvODmLukQXYw7N9QK2Ddo6ovjXAjO4kPIt6YTlupzVBbT9E7R/8yO0frbwAAAP//"
        resources:
          requests:
            cpu: 500m
            memory: 120Mi
      # InitContainer to create the ApplicationAccess database and objects in Postgresql
      initContainers:
      - name: postgresql-database-creation
        image: alpine:latest
        command: ['sh', '-c', 'until nc -zv postgresql-service 5432; do echo waiting for postgresql; sleep 2; done; apk --update add bash; apk --update add curl; curl -O https://raw.githubusercontent.com/alastairwyse/ApplicationAccessDeployment/refs/heads/master/InitializePostreSqlDatabase/InitializePostreSqlDatabase.sh; chmod 0777 InitializePostreSqlDatabase.sh; ./InitializePostreSqlDatabase.sh postgresql-service 5432 postgres; exit;']
        env:
        - name: PGPASSWORD
          value: "h8en9s8N"
        resources:
          requests:
            cpu: 250m
            memory: 250Mi

---
# Expose port 5000 publically (and route to the ApplicationAccess pod)
apiVersion: v1
kind: Service
metadata:
  name: applicationaccesslite-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: applicationaccesslite
  type: LoadBalancer